# kuka_arm_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - joint_a1
#     - joint_a2
#     - joint_a3
#     - joint_a4
#     - joint_a5
#     - joint_a6
#   gains:
#     joint_a1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_a2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_a3:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_a4:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_a5:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint_a6:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# gripper_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - finger_joint
#   gains:
#     finger_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  gains:
    joint_a1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_a6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper:
  type: "position_controllers/GripperActionController"
  joint: finger_joint
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      
  - name: gripper
    action_ns: gripper_cmd
    type: GripperCommand
    joints: 
      - finger_joint